version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
      - ./db.sqlite3:/app/db.sqlite3   # база хранится рядом с проектом
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - DEBUG=1
      # DATABASE_URL не указываем – Django сам возьмёт SQLite из settings.development
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        python manage.py runserver 0.0.0.0:8000"

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    stdin_open: true
    tty: true