version: "3.9"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: hub42
      MYSQL_USER: hub42
      MYSQL_PASSWORD: hub42pass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - staticfiles:/app/staticfiles
      - media:/app/media
      - ./logs:/app/logs
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DEBUG=0
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=hub42
      - DB_USER=hub42
      - DB_PASSWORD=hub42pass
      - DB_HOST=db
      - DB_PORT=3306
      - LOG_DIR=/app/logs
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db

  frontend-build:
    build:
      context: .
      dockerfile: Dockerfile.front
    volumes:
      - react_build:/build

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - react_build:/usr/share/nginx/html
      - staticfiles:/usr/share/nginx/static
      - media:/usr/share/nginx/media
    depends_on:
      - web
      - frontend-build

volumes:
  mysql_data:
  staticfiles:
  media:
  react_build: