# Generated by Django 5.0 on 2025-08-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('implementation', 'Внедрение 3D-принтера'), ('custom_equipment', 'Разработка оборудования под ключ')], default=' 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
