# Generated by Django 5.0 on 2025-08-20 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('tagline', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='equipment/')),
                ('is_published', models.BooleanField(default=True)),
                ('max_temperature', models.PositiveIntegerField(default=300, verbose_name='Макс. температура °C')),
                ('build_volume', models.CharField(blank=True, max_length=32, verbose_name='Рабочая область')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена, ₽')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='equipment.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Printer',
        ),
    ]
