# Generated by Django 5.0 on 2025-08-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='company',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
