# Generated by Django 5.2.7 on 2025-11-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='is_system',
            field=models.BooleanField(default=False, editable=False, verbose_name='Системная ссылка'),
        ),
    ]
